import React from "react";
import Head from "next/head";
import NavbarCustom from "./../components/NavbarCustom";

const Layout = ({ children }) => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <NavbarCustom />
      <main>{children}</main>

      <footer>
        <p>Footer</p>
      </footer>
    </>
  );
};

export default Layout;
